### ISSUE TITLE
Music playing only out of right speaker?

### ISSUE THREAD

**Issue by camdenorrb** [Gnar-Team/Gnar-bot#11]
I've compared playing from the source to playing through Gnar and have noticed that it uses only one side of the speaker for me. Is this a issue with Gnar or Discord?

**Comment by Avarel** [comment]
Discord issue.

**Comment by camdenorrb** [comment]
Wasn't headphones, was directly through the speakers.

**Comment by camdenorrb** [comment]
"'Accessibility > Audio' and select 'play stereo as mono.'"

Fixedz :3
