### ISSUE TITLE
Improper string formatting for song titles with brackets

### ISSUE THREAD

**Issue by hvze** [Gnar-Team/Gnar-bot#17]
![Preview](https://i.imgur.com/98O572d.png)

As seen in the image above, song titles with I presume brackets break the formatting.
I will probably create a path for this later today.

**Comment by hvze** [comment]
The issue lies [here](https://github.com/Gnar-Team/Gnar-bot/blob/db4c3007b68fbdc838bc494137edb8bed610b197/src/main/kotlin/xyz/gnarbot/gnar/music/MusicManager.kt#L226), but I cannot recreate this myself, only the bot can. Any ideas?

**Comment by RealBlackB1RD** [comment]
Missing permissions:
http://prntscr.com/i19i6b
