### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by Bituu** [Gnar-Team/Gnar-bot#24]
Gnar suddenly stops midsong for a few seconds and then plays along the moment he stopped, there is no problem with the internet connection though. And he just left the channel he was playing in even though the song should still be playing and the queue is not empty.

**Comment by RALMAZ** [comment]
Several times a minute

Gnar absolutely does not want to sing to us :-(

**Comment by RALMAZ** [comment]
@Avarel help us
